# Site settings
lang: en
title: "PyTorch Philippines"
author: "PyTorch Philippines"
default_author: "PyTorch Philippines"
description: >-
  PyTorch Philippines is a nationwide, community-led network for people who learn, teach,
  research, and build with PyTorch across Luzon, Visayas, and Mindanao.
latest_version: 1.0
timezone: Asia/Manila
url: "https://pytorch.ph"
baseurl: ""
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  # - jekyll-autoprefixer  # Not compatible with Ruby 3.4 - using alternative approach
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed
  sourcemap: never
  quiet_deps: true
exclude: [
    vendor,
    node_modules,
    README.md,
    CODE_OF_CONDUCT.md,
    Gemfile,
    Gemfile.lock,
    LICENSE,
    yarn.lock,
    yarn-error.log,
    package.json,
    package-lock.json,
    Makefile,
    NOTICE.md,
    scripts,
    docs,
    install.sh,
    install_basics.sh,
    install_nightlies.sh,
    preview_hub.sh,
    run_pytorch.sh,
    sanity_check.py,
    setup_ci.sh,
    upgrade_torchvision.sh,
  ]
include: [
    .nojekyll,
    CNAME,
    _static,
    _images,
    _modules,
    _sources,
    _tensor_str.html,
    _utils.html,
  ]
keep_files: [
    vendor/assets,
    docs/master/_static/js/vendor/
  ]
livereload: true
markdown: kramdown
highlighter: rouge

# Jekyll Collections: Blog, Events, Hub, News, Resources, ...
collections:
  posts:
    output: true
    permalink: /blog/:year/:title/
  contributors:
    output: true
  events:
    output: true
    permalink: /events/:path/
  features:
    output: false
  get_started:
    output: true
  news:
    output: true
    permalink: /news/:title/

# Blog Pagination
pagination:
  enabled: true
  per_page: 7
  permalink: "/blog/:num/"
  title: ":title | Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Variables
repository: PyTorchPH/PyTorchPH.github.io

# External URLs
external_urls:
  org_www: https://pytorch.org
  org_docs: https://docs.pytorch.org/docs
  org_tutorials: https://docs.pytorch.org/tutorials
  org_hub: https://pytorch.org/hub
  org_forums: https://discuss.pytorch.org
  org_landscape: https://landscape.pytorch.org
  org_coc: https://pytorch.org/code-of-conduct/
  previous_pytorch_versions: https://pytorch.org/get-started/previous-versions/
  repo_org: https://github.com/PyTorchPH
  repo_www: https://github.com/PyTorchPH/PyTorchPH.github.io
