import { FileText } from "lucide-react";

// Resume PDFs are rendered by the live portal server, so the static demo shows a placeholder
// inside the Resume Studio preview frame instead of a broken page.
export default function ResumeViewerPage() {
  return <main className="flex min-h-screen items-center justify-center bg-[#0d0d0d] p-6 text-center text-[#FFF7ED]">
    <div className="max-w-sm space-y-3">
      <FileText className="mx-auto text-orange-400" size={28} />
      <h1 className="text-lg font-semibold">Resume preview</h1>
      <p className="text-sm leading-6 text-[#FFF7ED]/60">PDF resumes are generated by the live portal from verified evidence. This static demo shows the workspace without rendering files.</p>
    </div>
  </main>;
}
